create table if not exists archive_items (
    id bigint generated by default as identity primary key,
    asset_id text not null,
    item_type text not null,
    content text not null,
    source text not null,
    location text,
    estimated_year text,
    people text,
    sensitivity text default 'public',
    duplicate_of text
);